# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1024']
-   repo: local
    hooks:
        - id: flake
          name: flake
          entry: .venv/bin/flake8
          args: ['--ignore=F821' ]
          language: system
          types:
              - python
        - id: isort
          name: isort
          args: [--check-only, --diff]
          entry: .venv/bin/isort
          language: system
          types:
              - python
        - id: black
          name: black
          args: [--check, --diff]
          entry: .venv/bin/black
          language: system
          types:
              - python
